.\"-
.\" Copyright (c) 2022 Dag-Erling Smørgrav
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. The name of the author may not be used to endorse or promote
.\"    products derived from this software without specific prior written
.\"    permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd May 15, 2022
.Dt CRYB_MD4 3
.Os
.Sh NAME
.Nm cryb_md4_init ,
.Nm cryb_md4_update ,
.Nm cryb_md4_final ,
.Nm cryb_md4_complete
.Nd Message-Digest Algorithm 2
.Sh LIBRARY
.Lb libcryb-digest
.Sh SYNOPSIS
.In stddef.h
.In stdint.h
.In cryb/md4.h
.Ft void
.Fn cryb_md4_init "cryb_md4_ctx *context"
.Ft void
.Fn cryb_md4_update "cryb_md4_ctx *context" "const void *data" "size_t len"
.Ft void
.Fn cryb_md4_final "cryb_md4_ctx *context" "uint8_t *digest"
.Ft void
.Fn cryb_md4_complete "const void *data" "size_t len" "uint8_t *digest"
.Sh DESCRIPTION
The
.Nm cryb_md4
family of functions implements the MD4 message digest algorithm as
described in RFC 1320.
.Pp
The
.Fn cryb_md4_init
function initializes the context structure pointed to by
.Va context .
It is the caller's responsibility to allocate this structure.
.Pp
The
.Fn cryb_md4_update
function hashes the next
.Va len
bytes of data pointed to by the
.Va data
pointer into the given hash context.
.Pp
The
.Fn cryb_md4_final
function finalizes the computation and writes the resulting message
digest to the caller-provided buffer pointed to by
.Va digest ,
which must be at least
.Dv MD4_DIGEST_LEN
bytes long.
It is the caller's responsibility to dispose of the context structure
after calling
.Fn cryb_md4_final .
.Pp
The
.Fn cryb_md4_complete
function is a shortcut to calling
.Fn cryb_md4_init ,
.Fn cryb_md4_update ,
and
.Fn cryb_md4_final
when the entire message is available up front in a single contiguous
buffer.
.Sh IMPLEMENTATION NOTES
The
.In cryb/md4.h
header provides macros which allows these functions and the context
type to be referred to without their
.Dq Li cryb_
prefix.
.Pp
The MD4 message digest algorithm has been proven to be vulnerable to
collision attacks and should not be used for cryptographic purposes.
.Sh SEE ALSO
.Xr cryb_digest 3 ,
.Xr cryb_md2 3 ,
.Xr cryb_md5 3
.Sh REFERENCES
.Rs
.%A Rivest, Ronald
.%T The MD4 Message-Digest Algorithm
.%D April 1992
.%O RFC 1320
.%U https://datatracker.ietf.org/doc/html/rfc1320
.Re
.Rs
.%A Turner, Sean
.%A Chen, Lily
.%T MD4 to Historic Status
.%D March 2011
.%O RFC 6150
.%U https://datatracker.ietf.org/doc/html/rfc6150
.Re
.Sh AUTHORS
These functions and this manual page were written by
.An Dag-Erling Sm\(/orgrav Aq Mt des@des.no .
