.\"-
.\" Copyright (c) 2022 Dag-Erling Smørgrav
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. The name of the author may not be used to endorse or promote
.\"    products derived from this software without specific prior written
.\"    permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd May 15, 2022
.Dt CRYB_FNV 3
.Os
.Sh NAME
.Nm cryb_fnv0_32_hash ,
.Nm cryb_fnv0_64_hash ,
.Nm cryb_fnv1_32_hash ,
.Nm cryb_fnv1_64_hash ,
.Nm cryb_fnv1a_32_hash ,
.Nm cryb_fnv1a_64_hash
.Nd non-cryptographic hash functions
.Sh LIBRARY
.Lb libcryb-hash
.Sh SYNOPSIS
.In stddef.h
.In stdint.h
.In cryb/hash.h
.Ft uint32_t
.Fn cryb_fnv0_32_hash "const void *data" "size_t len"
.Ft uint64_t
.Fn cryb_fnv0_64_hash "const void *data" "size_t len"
.Ft uint32_t
.Fn cryb_fnv1_32_hash "const void *data" "size_t len"
.Ft uint64_t
.Fn cryb_fnv1_64_hash "const void *data" "size_t len"
.Ft uint32_t
.Fn cryb_fnv1a_32_hash "const void *data" "size_t len"
.Ft uint64_t
.Fn cryb_fnv1a_64_hash "const void *data" "size_t len"
.Sh DESCRIPTION
The
.Fn cryb_fnv0_32_hash ,
.Fn cryb_fnv1_32_hash ,
and
.Fn cryb_fnv1a_32_hash ,
functions return a 32-bit hash of the
.Va len
first bytes of the object pointed to by
.Va data
using the Fowler-Noll-Vo (FNV) 0, 1, and 1a algorithms respectively.
.Pp
The
.Fn cryb_fnv0_64_hash ,
.Fn cryb_fnv1_64_hash ,
and
.Fn cryb_fnv1a_64_hash ,
functions return a 64-bit hash of the
.Va len
first bytes of the object pointed to by
.Va data
using the FNV 0, 1, and 1a algorithms respectively.
.Sh IMPLEMENTATION NOTES
The
.In cryb/hash.h
header provides macros which allows these functions to be referred to
without their
.Dq Li cryb_
prefix.
.Sh SEE ALSO
.Xr cryb_hash 3
.Sh STANDARDS
.Rs
.%A Fowler, Glenn
.%A Noll, Landon Curt
.%A Vo, Kiem-Phong
.%A Eastlake, Donald
.%A Hansen, Tony
.%T The FNV Non-Cryptographic Hash Algorithm
.%D May 29, 2019
.%O draft-eastlake-fnv-17
.%U https://datatracker.ietf.org/doc/html/draft-eastlake-fnv-17
.Re
.Sh AUTHORS
The
.Fn cryb_pearson_hash
and
.Fn cryb_pearson_hash_str
functions and this manual page were written by
.An Dag-Erling Sm\(/orgrav Aq Mt des@des.no .
